[package]
name = "pods"
version = "1.0.0-beta.6"
authors = ["Marcus Behrendt <marcus.behrendt.86@gmail.com>"]
edition = "2021"

[dependencies]
adw = { version = "0.2.0-alpha.3", package = "libadwaita", features = ["v1_2"] }
anyhow = "1.0"
ashpd = { version = "0.3", features = ["feature_gtk4"] }
futures = { version = "0.3", default-features = false }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.4", package = "gtk4", features = ["v4_6"] }
indexmap = { version = "1.7", features = ["serde"] }
log = "0.4"
names = { version = "0.14", default-features = false }
once_cell = "1.9"
paste = "1.0"
podman-api = { git = "https://github.com/marhkb/podman-api-rs.git", branch = "staging", default-features = false }
serde = "1.0"
serde_json = "1.0"
sourceview5 = "0.4"
syslog = "6.0"
tokio = { version = "1", features = ["fs", "io-util", "process", "rt-multi-thread"] }
vte = "0.11"
