[package]
name = "pods"
version = "1.0.0-beta.6"
authors = ["Marcus Behrendt <marcus.behrendt.86@gmail.com>"]
edition = "2021"

[dependencies]
adw = { version = "0.2", package = "libadwaita", features = ["v1_2"] }
anyhow = "1"
ashpd = { version = "0.4.0-alpha.1", features = ["gtk4"] }
futures = { version = "0.3", default-features = false }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.5", package = "gtk4", features = ["v4_8"] }
indexmap = { version = "1", features = ["serde"] }
log = "0.4"
names = { version = "0.14", default-features = false }
once_cell = "1"
paste = "1"
podman-api = { git = "https://github.com/vv9k/podman-api-rs.git", default-features = false }
serde = "1"
serde_json = "1"
sourceview5 = "0.5"
syslog = "6"
tokio = { version = "1", features = ["fs", "io-util", "process", "rt-multi-thread"] }
vte = "0.11"
